### ISSUE TITLE
Question about colouring direct function call

### ISSUE THREAD

**Issue by srggrs** [dunovank/jupyterlab_darkside_ui#1]
Thank you so much for this, I really love the color palette and combos! Just a question, why you decide not to color when the function is called directly (e.g. declared in same script/notebook or imported), while is colored if called from a module (see image below). Thx
![image](https://user-images.githubusercontent.com/34258464/116077265-a10c0b80-a6d8-11eb-9eab-50a07df4ddfa.png)

**Comment by dunovank** [comment]
Glad you like it! I'm not sure if there's an easy selector for highlighting a locally-defined function call. However, I believe when calling a function defined in a module it gets treated as a "property" or "attribute" from CodeMirror's perspective (which controls syntax highlighting).

**Comment by dunovank** [comment]
Please close the issue if there are no additional follow ups.
