### ISSUE TITLE
Statusbar gone?

### ISSUE THREAD

**Issue by michaelaye** [dunovank/jupyterlab_darkside_ui#4]
Using JLab 3.2.5, when switching on this beautiful theme, the statusbar is gone, which unfortunately I cannot live without.
Any way to get the statusbar back in?

![image](https://user-images.githubusercontent.com/69774/145938453-bf8afdd0-4f57-4706-99ba-e5ad797f2b77.png)

Here's the official dark theme that supports the status bar:

![image](https://user-images.githubusercontent.com/69774/145938483-e577d38a-3310-4368-aede-e7c9df572ff0.png)

**Comment by michaelaye** [comment]
I just noticed that the statusbar briefly flashed up and then goes away after activating the theme.

**Comment by dunovank** [comment]
Hm.. Not sure where this is happening in the code but I will certainly look into it.

**Comment by dunovank** [comment]
Still trying to pin this down, just wanted to say that if anyone has any idea as to how to re-surface the status bar I'd invite any tips (or better yet, a PR). Had some time to do a cursory look through the code today, no dice. Probably a bad copy/paste somewhere in the [style/variables.css](https://github.com/dunovank/jupyterlab_darkside_ui/blob/master/style/variables.css) file.

**Comment by dunovank** [comment]
Confirmed PR #7 fixes this issue - just published an update to PyPI (v0.2.3). Marking this closed. Thanks again @diegombar
