### ISSUE TITLE
dependency issues

### ISSUE THREAD

**Issue by michaelaye** [dunovank/jupyterlab_darkside_ui#8]
An installation of this theme currently requires downgrades of:

* jedi (from 0.18.1 to 0.17.2)
* nbconvert (from 6.4.4 to 5.6.1)
* parso (from 0.8.3 to 0.7.1)

Could it be checked if these dependencies are really strictly required, or if they could be relaxed to the current minor versions ?

**Comment by dunovank** [comment]
(Probably) yes, I will look into updating these dependencies when I have some free time.

**Comment by dunovank** [comment]
This was resolved a few months back, forgot to close it. Thanks for the contribution!
